// <auto-generated />
using System;
using DisplayControl.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace DisplayControl.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(DisplayControlDbContext))]
    [Migration("20260815152308_ContentAndAssignmentCore")]
    partial class ContentAndAssignmentCore
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("app")
                .HasAnnotation("ProductVersion", "10.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("DisplayControl.Domain.Content.ContentAsset", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset?>("ArchivedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("archived_at_utc");

                    b.Property<Guid>("ConcurrencyToken")
                        .IsConcurrencyToken()
                        .HasColumnType("uuid")
                        .HasColumnName("concurrency_token");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<Guid>("CreatedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by_user_id");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("description");

                    b.Property<string>("LifecycleState")
                        .IsRequired()
                        .HasMaxLength(24)
                        .HasColumnType("character varying(24)")
                        .HasColumnName("lifecycle_state");

                    b.Property<string>("MediaKind")
                        .IsRequired()
                        .HasMaxLength(24)
                        .HasColumnType("character varying(24)")
                        .HasColumnName("media_kind");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("title");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.HasKey("Id")
                        .HasName("pk_content_assets");

                    b.HasAlternateKey("TenantId", "Id")
                        .HasName("ak_content_assets_tenant_id_id");

                    b.HasIndex("TenantId", "Title")
                        .HasDatabaseName("ix_content_assets_tenant_title");

                    b.ToTable("content_assets", "app");
                });

            modelBuilder.Entity("DisplayControl.Domain.Content.ContentVersion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset?>("ApprovedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("approved_at_utc");

                    b.Property<Guid?>("ApprovedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("approved_by_user_id");

                    b.Property<long>("ByteLength")
                        .HasColumnType("bigint")
                        .HasColumnName("byte_length");

                    b.Property<Guid>("ContentAssetId")
                        .HasColumnType("uuid")
                        .HasColumnName("content_asset_id");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<Guid>("CreatedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by_user_id");

                    b.Property<string>("DetectedMimeType")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("detected_mime_type");

                    b.Property<string>("MediaMetadataJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("media_metadata_json");

                    b.Property<string>("OriginalDisplayFileName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("original_display_file_name");

                    b.Property<string>("RejectionCode")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("rejection_code");

                    b.Property<string>("ScanEngineVersion")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("scan_engine_version");

                    b.Property<string>("ScanState")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("scan_state");

                    b.Property<byte[]>("Sha256")
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasColumnName("sha256");

                    b.Property<string>("StorageKey")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("storage_key");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<int>("VersionNumber")
                        .HasColumnType("integer")
                        .HasColumnName("version_number");

                    b.HasKey("Id")
                        .HasName("pk_content_versions");

                    b.HasAlternateKey("TenantId", "Id")
                        .HasName("ak_content_versions_tenant_id_id");

                    b.HasIndex("TenantId", "StorageKey")
                        .IsUnique()
                        .HasDatabaseName("ux_content_versions_tenant_storage_key");

                    b.HasIndex("TenantId", "ContentAssetId", "VersionNumber")
                        .IsUnique()
                        .HasDatabaseName("ux_content_versions_asset_version");

                    b.ToTable("content_versions", "app", t =>
                        {
                            t.HasCheckConstraint("ck_content_versions_byte_length", "byte_length >= 0");

                            t.HasCheckConstraint("ck_content_versions_sha256", "octet_length(sha256) = 32");

                            t.HasCheckConstraint("ck_content_versions_version", "version_number > 0");
                        });
                });

            modelBuilder.Entity("DisplayControl.Domain.Devices.Device", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AgentVersion")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("agent_version");

                    b.Property<long?>("AppliedManifestVersion")
                        .HasColumnType("bigint")
                        .HasColumnName("applied_manifest_version");

                    b.Property<string>("Architecture")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("architecture");

                    b.Property<Guid>("ConcurrencyToken")
                        .IsConcurrencyToken()
                        .HasColumnType("uuid")
                        .HasColumnName("concurrency_token");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<long?>("DiskCapacityBytes")
                        .HasColumnType("bigint")
                        .HasColumnName("disk_capacity_bytes");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)")
                        .HasColumnName("display_name");

                    b.Property<string>("Hostname")
                        .HasMaxLength(253)
                        .HasColumnType("character varying(253)")
                        .HasColumnName("hostname");

                    b.Property<DateTimeOffset?>("LastSeenUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_seen_utc");

                    b.Property<string>("OsDescription")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("os_description");

                    b.Property<string>("PlaybackHealthCode")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("playback_health_code");

                    b.Property<string>("PlayerVersion")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("player_version");

                    b.Property<string>("SerialNumberNormalized")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("serial_number_normalized");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("state");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.HasKey("Id")
                        .HasName("pk_devices");

                    b.HasAlternateKey("TenantId", "Id")
                        .HasName("ak_devices_tenant_id_id");

                    b.HasIndex("TenantId", "SerialNumberNormalized")
                        .IsUnique()
                        .HasDatabaseName("ux_devices_tenant_serial")
                        .HasFilter("serial_number_normalized IS NOT NULL");

                    b.ToTable("devices", "app");
                });

            modelBuilder.Entity("DisplayControl.Domain.Devices.DeviceGroup", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("ConcurrencyToken")
                        .IsConcurrencyToken()
                        .HasColumnType("uuid")
                        .HasColumnName("concurrency_token");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<Guid>("CreatedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by_user_id");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)")
                        .HasColumnName("name");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.HasKey("Id")
                        .HasName("pk_device_groups");

                    b.HasAlternateKey("TenantId", "Id")
                        .HasName("ak_device_groups_tenant_id_id");

                    b.HasIndex("TenantId", "Name")
                        .IsUnique()
                        .HasDatabaseName("ux_device_groups_tenant_name");

                    b.ToTable("device_groups", "app");
                });

            modelBuilder.Entity("DisplayControl.Domain.Devices.DeviceGroupMember", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("AddedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("added_at_utc");

                    b.Property<Guid>("AddedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("added_by_user_id");

                    b.Property<Guid>("DeviceGroupId")
                        .HasColumnType("uuid")
                        .HasColumnName("device_group_id");

                    b.Property<Guid>("DeviceId")
                        .HasColumnType("uuid")
                        .HasColumnName("device_id");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.HasKey("Id")
                        .HasName("pk_device_group_members");

                    b.HasAlternateKey("TenantId", "Id")
                        .HasName("ak_device_group_members_tenant_id_id");

                    b.HasIndex("TenantId", "DeviceId");

                    b.HasIndex("TenantId", "DeviceGroupId", "DeviceId")
                        .IsUnique()
                        .HasDatabaseName("ux_device_group_members_group_device");

                    b.ToTable("device_group_members", "app");
                });

            modelBuilder.Entity("DisplayControl.Domain.Licensing.DeviceLicense", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("ConcurrencyToken")
                        .IsConcurrencyToken()
                        .HasColumnType("uuid")
                        .HasColumnName("concurrency_token");

                    b.Property<string>("ControlState")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("control_state");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<Guid>("DeviceId")
                        .HasColumnType("uuid")
                        .HasColumnName("device_id");

                    b.Property<DateTimeOffset>("ExpiresAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at_utc");

                    b.Property<DateTimeOffset?>("LatestIssuedLeaseExpiryUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("latest_issued_lease_expiry_utc");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<Guid?>("TransferDestinationDeviceId")
                        .HasColumnType("uuid")
                        .HasColumnName("transfer_destination_device_id");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.Property<DateTimeOffset>("ValidFromUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("valid_from_utc");

                    b.HasKey("Id")
                        .HasName("pk_licenses");

                    b.HasAlternateKey("TenantId", "Id")
                        .HasName("ak_licenses_tenant_id_id");

                    b.HasIndex("TenantId", "DeviceId")
                        .HasDatabaseName("ix_licenses_tenant_device");

                    b.ToTable("licenses", "app", t =>
                        {
                            t.HasCheckConstraint("ck_licenses_window", "expires_at_utc > valid_from_utc");
                        });
                });

            modelBuilder.Entity("DisplayControl.Domain.Licensing.LicenseEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("ActorId")
                        .HasColumnType("uuid")
                        .HasColumnName("actor_id");

                    b.Property<string>("ActorType")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("actor_type");

                    b.Property<string>("AfterJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("after_json");

                    b.Property<string>("BeforeJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("before_json");

                    b.Property<Guid?>("DestinationDeviceId")
                        .HasColumnType("uuid")
                        .HasColumnName("destination_device_id");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("event_type");

                    b.Property<Guid>("LicenseId")
                        .HasColumnType("uuid")
                        .HasColumnName("license_id");

                    b.Property<DateTimeOffset>("OccurredAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_at_utc");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("reason");

                    b.Property<Guid?>("SourceDeviceId")
                        .HasColumnType("uuid")
                        .HasColumnName("source_device_id");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.HasKey("Id")
                        .HasName("pk_license_events");

                    b.HasAlternateKey("TenantId", "Id")
                        .HasName("ak_license_events_tenant_id_id");

                    b.HasIndex("TenantId", "LicenseId", "OccurredAtUtc")
                        .HasDatabaseName("ix_license_events_license_occurred");

                    b.ToTable("license_events", "app");
                });

            modelBuilder.Entity("DisplayControl.Domain.Operations.OutboxMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("AttemptCount")
                        .HasColumnType("integer")
                        .HasColumnName("attempt_count");

                    b.Property<string>("LastSafeError")
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)")
                        .HasColumnName("last_safe_error");

                    b.Property<string>("MessageType")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)")
                        .HasColumnName("message_type");

                    b.Property<DateTimeOffset>("OccurredAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_at_utc");

                    b.Property<string>("PayloadJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("payload_json");

                    b.Property<DateTimeOffset?>("ProcessedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("processed_at_utc");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.HasKey("Id")
                        .HasName("pk_outbox_messages");

                    b.HasAlternateKey("TenantId", "Id")
                        .HasName("ak_outbox_messages_tenant_id_id");

                    b.HasIndex("ProcessedAtUtc", "OccurredAtUtc")
                        .HasDatabaseName("ix_outbox_pending");

                    b.ToTable("outbox_messages", "app");
                });

            modelBuilder.Entity("DisplayControl.Domain.Operations.SystemKeyMetadata", b =>
                {
                    b.Property<string>("KeyId")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("key_id");

                    b.Property<DateTimeOffset>("ActivatesAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("activates_at_utc");

                    b.Property<string>("Algorithm")
                        .IsRequired()
                        .HasMaxLength(24)
                        .HasColumnType("character varying(24)")
                        .HasColumnName("algorithm");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<byte[]>("PublicKeyDer")
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasColumnName("public_key_der");

                    b.Property<string>("Purpose")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("purpose");

                    b.Property<DateTimeOffset?>("RetiresAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("retires_at_utc");

                    b.HasKey("KeyId")
                        .HasName("pk_system_key_metadata");

                    b.HasIndex("Purpose", "ActivatesAtUtc")
                        .HasDatabaseName("ix_system_keys_purpose_activation");

                    b.ToTable("system_key_metadata", "app");
                });

            modelBuilder.Entity("DisplayControl.Domain.Operations.TenantAuditEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("action");

                    b.Property<Guid?>("ActorId")
                        .HasColumnType("uuid")
                        .HasColumnName("actor_id");

                    b.Property<string>("ActorType")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("actor_type");

                    b.Property<Guid>("CorrelationId")
                        .HasColumnType("uuid")
                        .HasColumnName("correlation_id");

                    b.Property<string>("DetailsJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("details_json");

                    b.Property<DateTimeOffset>("OccurredAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_at_utc");

                    b.Property<string>("Outcome")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("outcome");

                    b.Property<string>("ReasonCode")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("reason_code");

                    b.Property<Guid?>("TargetId")
                        .HasColumnType("uuid")
                        .HasColumnName("target_id");

                    b.Property<string>("TargetType")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("target_type");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.HasKey("Id")
                        .HasName("pk_audit_events");

                    b.HasAlternateKey("TenantId", "Id")
                        .HasName("ak_audit_events_tenant_id_id");

                    b.HasIndex("TenantId", "OccurredAtUtc")
                        .HasDatabaseName("ix_audit_events_tenant_occurred");

                    b.ToTable("audit_events", "app");
                });

            modelBuilder.Entity("DisplayControl.Domain.Playlists.Playlist", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset?>("ArchivedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("archived_at_utc");

                    b.Property<Guid>("ConcurrencyToken")
                        .IsConcurrencyToken()
                        .HasColumnType("uuid")
                        .HasColumnName("concurrency_token");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<Guid>("CreatedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by_user_id");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.HasKey("Id")
                        .HasName("pk_playlists");

                    b.HasAlternateKey("TenantId", "Id")
                        .HasName("ak_playlists_tenant_id_id");

                    b.HasIndex("TenantId", "Name")
                        .HasDatabaseName("ix_playlists_tenant_name");

                    b.ToTable("playlists", "app");
                });

            modelBuilder.Entity("DisplayControl.Domain.Playlists.PlaylistItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("ContentVersionId")
                        .HasColumnType("uuid")
                        .HasColumnName("content_version_id");

                    b.Property<int?>("DurationMilliseconds")
                        .HasColumnType("integer")
                        .HasColumnName("duration_milliseconds");

                    b.Property<bool>("LoopVideo")
                        .HasColumnType("boolean")
                        .HasColumnName("loop_video");

                    b.Property<Guid>("PlaylistVersionId")
                        .HasColumnType("uuid")
                        .HasColumnName("playlist_version_id");

                    b.Property<int>("Position")
                        .HasColumnType("integer")
                        .HasColumnName("position");

                    b.Property<string>("PresentationJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("presentation_json");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.HasKey("Id")
                        .HasName("pk_playlist_items");

                    b.HasAlternateKey("TenantId", "Id")
                        .HasName("ak_playlist_items_tenant_id_id");

                    b.HasIndex("TenantId", "ContentVersionId");

                    b.HasIndex("TenantId", "PlaylistVersionId", "Position")
                        .IsUnique()
                        .HasDatabaseName("ux_playlist_items_version_position");

                    b.ToTable("playlist_items", "app", t =>
                        {
                            t.HasCheckConstraint("ck_playlist_items_duration", "duration_milliseconds IS NULL OR duration_milliseconds > 0");

                            t.HasCheckConstraint("ck_playlist_items_position", "position >= 0");
                        });
                });

            modelBuilder.Entity("DisplayControl.Domain.Playlists.PlaylistVersion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<Guid>("CreatedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by_user_id");

                    b.Property<string>("DescriptionSnapshot")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("description_snapshot");

                    b.Property<string>("NameSnapshot")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name_snapshot");

                    b.Property<Guid>("PlaylistId")
                        .HasColumnType("uuid")
                        .HasColumnName("playlist_id");

                    b.Property<string>("PublicationState")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("publication_state");

                    b.Property<DateTimeOffset?>("PublishedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("published_at_utc");

                    b.Property<Guid?>("PublishedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("published_by_user_id");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<int>("VersionNumber")
                        .HasColumnType("integer")
                        .HasColumnName("version_number");

                    b.HasKey("Id")
                        .HasName("pk_playlist_versions");

                    b.HasAlternateKey("TenantId", "Id")
                        .HasName("ak_playlist_versions_tenant_id_id");

                    b.HasIndex("TenantId", "PlaylistId", "VersionNumber")
                        .IsUnique()
                        .HasDatabaseName("ux_playlist_versions_playlist_version");

                    b.ToTable("playlist_versions", "app", t =>
                        {
                            t.HasCheckConstraint("ck_playlist_versions_version", "version_number > 0");
                        });
                });

            modelBuilder.Entity("DisplayControl.Domain.Scheduling.DesiredState", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<Guid>("DeviceId")
                        .HasColumnType("uuid")
                        .HasColumnName("device_id");

                    b.Property<DateTimeOffset?>("EndsAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ends_at_utc");

                    b.Property<byte[]>("ManifestSha256")
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasColumnName("manifest_sha256");

                    b.Property<DateTimeOffset>("PublishedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("published_at_utc");

                    b.Property<Guid?>("SourceDeviceAssignmentId")
                        .HasColumnType("uuid")
                        .HasColumnName("source_device_assignment_id");

                    b.Property<Guid?>("SourceGroupAssignmentId")
                        .HasColumnType("uuid")
                        .HasColumnName("source_group_assignment_id");

                    b.Property<DateTimeOffset?>("StartsAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("starts_at_utc");

                    b.Property<Guid?>("SupersededByDesiredStateId")
                        .HasColumnType("uuid")
                        .HasColumnName("superseded_by_desired_state_id");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<long>("Version")
                        .HasColumnType("bigint")
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("pk_desired_states");

                    b.HasAlternateKey("TenantId", "Id")
                        .HasName("ak_desired_states_tenant_id_id");

                    b.HasIndex("TenantId", "SourceDeviceAssignmentId");

                    b.HasIndex("TenantId", "SourceGroupAssignmentId");

                    b.HasIndex("TenantId", "SupersededByDesiredStateId");

                    b.HasIndex("TenantId", "DeviceId", "Version")
                        .IsUnique()
                        .HasDatabaseName("ux_desired_states_device_version");

                    b.ToTable("desired_states", "app", t =>
                        {
                            t.HasCheckConstraint("ck_desired_states_sha256", "octet_length(manifest_sha256) = 32");

                            t.HasCheckConstraint("ck_desired_states_source", "(source_device_assignment_id IS NOT NULL AND source_group_assignment_id IS NULL) OR (source_device_assignment_id IS NULL AND source_group_assignment_id IS NOT NULL)");

                            t.HasCheckConstraint("ck_desired_states_version", "version > 0");

                            t.HasCheckConstraint("ck_desired_states_window", "starts_at_utc IS NULL OR ends_at_utc IS NULL OR ends_at_utc > starts_at_utc");
                        });
                });

            modelBuilder.Entity("DisplayControl.Domain.Scheduling.DesiredStateAsset", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<long>("ByteLength")
                        .HasColumnType("bigint")
                        .HasColumnName("byte_length");

                    b.Property<Guid>("ContentVersionId")
                        .HasColumnType("uuid")
                        .HasColumnName("content_version_id");

                    b.Property<Guid>("DesiredStateId")
                        .HasColumnType("uuid")
                        .HasColumnName("desired_state_id");

                    b.Property<int?>("DurationMilliseconds")
                        .HasColumnType("integer")
                        .HasColumnName("duration_milliseconds");

                    b.Property<bool>("LoopVideo")
                        .HasColumnType("boolean")
                        .HasColumnName("loop_video");

                    b.Property<string>("MediaKind")
                        .IsRequired()
                        .HasMaxLength(24)
                        .HasColumnType("character varying(24)")
                        .HasColumnName("media_kind");

                    b.Property<string>("PlaybackJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("playback_json");

                    b.Property<int>("Position")
                        .HasColumnType("integer")
                        .HasColumnName("position");

                    b.Property<byte[]>("Sha256")
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasColumnName("sha256");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.HasKey("Id")
                        .HasName("pk_desired_state_assets");

                    b.HasAlternateKey("TenantId", "Id")
                        .HasName("ak_desired_state_assets_tenant_id_id");

                    b.HasIndex("TenantId", "ContentVersionId");

                    b.HasIndex("TenantId", "DesiredStateId", "Position")
                        .IsUnique()
                        .HasDatabaseName("ux_desired_state_assets_state_position");

                    b.ToTable("desired_state_assets", "app", t =>
                        {
                            t.HasCheckConstraint("ck_desired_state_assets_byte_length", "byte_length >= 0");

                            t.HasCheckConstraint("ck_desired_state_assets_duration", "duration_milliseconds IS NULL OR duration_milliseconds > 0");

                            t.HasCheckConstraint("ck_desired_state_assets_position", "position >= 0");

                            t.HasCheckConstraint("ck_desired_state_assets_sha256", "octet_length(sha256) = 32");
                        });
                });

            modelBuilder.Entity("DisplayControl.Domain.Scheduling.DeviceAssignment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("ConcurrencyToken")
                        .IsConcurrencyToken()
                        .HasColumnType("uuid")
                        .HasColumnName("concurrency_token");

                    b.Property<Guid>("DeviceId")
                        .HasColumnType("uuid")
                        .HasColumnName("device_id");

                    b.Property<DateTimeOffset?>("EndsAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ends_at_utc");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("boolean")
                        .HasColumnName("is_enabled");

                    b.Property<Guid>("PlaylistVersionId")
                        .HasColumnType("uuid")
                        .HasColumnName("playlist_version_id");

                    b.Property<string>("PresentationTimeZone")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("presentation_time_zone");

                    b.Property<int>("Priority")
                        .HasColumnType("integer")
                        .HasColumnName("priority");

                    b.Property<DateTimeOffset>("PublishedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("published_at_utc");

                    b.Property<Guid>("PublishedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("published_by_user_id");

                    b.Property<DateTimeOffset?>("StartsAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("starts_at_utc");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.HasKey("Id")
                        .HasName("pk_device_assignments");

                    b.HasAlternateKey("TenantId", "Id")
                        .HasName("ak_device_assignments_tenant_id_id");

                    b.HasIndex("TenantId", "PlaylistVersionId");

                    b.HasIndex("TenantId", "DeviceId", "IsEnabled", "Priority")
                        .HasDatabaseName("ix_device_assignments_resolution");

                    b.ToTable("device_assignments", "app", t =>
                        {
                            t.HasCheckConstraint("ck_device_assignments_window", "starts_at_utc IS NULL OR ends_at_utc IS NULL OR ends_at_utc > starts_at_utc");
                        });
                });

            modelBuilder.Entity("DisplayControl.Domain.Scheduling.GroupAssignment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("ConcurrencyToken")
                        .IsConcurrencyToken()
                        .HasColumnType("uuid")
                        .HasColumnName("concurrency_token");

                    b.Property<Guid>("DeviceGroupId")
                        .HasColumnType("uuid")
                        .HasColumnName("device_group_id");

                    b.Property<DateTimeOffset?>("EndsAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ends_at_utc");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("boolean")
                        .HasColumnName("is_enabled");

                    b.Property<Guid>("PlaylistVersionId")
                        .HasColumnType("uuid")
                        .HasColumnName("playlist_version_id");

                    b.Property<string>("PresentationTimeZone")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("presentation_time_zone");

                    b.Property<int>("Priority")
                        .HasColumnType("integer")
                        .HasColumnName("priority");

                    b.Property<DateTimeOffset>("PublishedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("published_at_utc");

                    b.Property<Guid>("PublishedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("published_by_user_id");

                    b.Property<DateTimeOffset?>("StartsAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("starts_at_utc");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.HasKey("Id")
                        .HasName("pk_group_assignments");

                    b.HasAlternateKey("TenantId", "Id")
                        .HasName("ak_group_assignments_tenant_id_id");

                    b.HasIndex("TenantId", "PlaylistVersionId");

                    b.HasIndex("TenantId", "DeviceGroupId", "IsEnabled", "Priority")
                        .HasDatabaseName("ix_group_assignments_resolution");

                    b.ToTable("group_assignments", "app", t =>
                        {
                            t.HasCheckConstraint("ck_group_assignments_window", "starts_at_utc IS NULL OR ends_at_utc IS NULL OR ends_at_utc > starts_at_utc");
                        });
                });

            modelBuilder.Entity("DisplayControl.Domain.Tenancy.Tenant", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("ConcurrencyToken")
                        .IsConcurrencyToken()
                        .HasColumnType("uuid")
                        .HasColumnName("concurrency_token");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)")
                        .HasColumnName("name");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("slug");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasMaxLength(24)
                        .HasColumnType("character varying(24)")
                        .HasColumnName("state");

                    b.Property<string>("TimeZone")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("time_zone");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.HasKey("Id")
                        .HasName("pk_tenants");

                    b.HasIndex("Slug")
                        .IsUnique()
                        .HasDatabaseName("ux_tenants_slug");

                    b.ToTable("tenants", "app");
                });

            modelBuilder.Entity("DisplayControl.Domain.Content.ContentAsset", b =>
                {
                    b.HasOne("DisplayControl.Domain.Tenancy.Tenant", null)
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_content_assets_tenants");
                });

            modelBuilder.Entity("DisplayControl.Domain.Content.ContentVersion", b =>
                {
                    b.HasOne("DisplayControl.Domain.Tenancy.Tenant", null)
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_content_versions_tenants");

                    b.HasOne("DisplayControl.Domain.Content.ContentAsset", null)
                        .WithMany()
                        .HasForeignKey("TenantId", "ContentAssetId")
                        .HasPrincipalKey("TenantId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_content_versions_assets_tenant");
                });

            modelBuilder.Entity("DisplayControl.Domain.Devices.Device", b =>
                {
                    b.HasOne("DisplayControl.Domain.Tenancy.Tenant", null)
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_devices_tenants");
                });

            modelBuilder.Entity("DisplayControl.Domain.Devices.DeviceGroup", b =>
                {
                    b.HasOne("DisplayControl.Domain.Tenancy.Tenant", null)
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_device_groups_tenants");
                });

            modelBuilder.Entity("DisplayControl.Domain.Devices.DeviceGroupMember", b =>
                {
                    b.HasOne("DisplayControl.Domain.Tenancy.Tenant", null)
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_device_group_members_tenants");

                    b.HasOne("DisplayControl.Domain.Devices.DeviceGroup", null)
                        .WithMany()
                        .HasForeignKey("TenantId", "DeviceGroupId")
                        .HasPrincipalKey("TenantId", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_device_group_members_groups_tenant");

                    b.HasOne("DisplayControl.Domain.Devices.Device", null)
                        .WithMany()
                        .HasForeignKey("TenantId", "DeviceId")
                        .HasPrincipalKey("TenantId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_device_group_members_devices_tenant");
                });

            modelBuilder.Entity("DisplayControl.Domain.Licensing.DeviceLicense", b =>
                {
                    b.HasOne("DisplayControl.Domain.Tenancy.Tenant", null)
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_licenses_tenants");

                    b.HasOne("DisplayControl.Domain.Devices.Device", null)
                        .WithMany()
                        .HasForeignKey("TenantId", "DeviceId")
                        .HasPrincipalKey("TenantId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_licenses_devices_tenant");
                });

            modelBuilder.Entity("DisplayControl.Domain.Licensing.LicenseEvent", b =>
                {
                    b.HasOne("DisplayControl.Domain.Tenancy.Tenant", null)
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_license_events_tenants");

                    b.HasOne("DisplayControl.Domain.Licensing.DeviceLicense", null)
                        .WithMany()
                        .HasForeignKey("TenantId", "LicenseId")
                        .HasPrincipalKey("TenantId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_license_events_licenses_tenant");
                });

            modelBuilder.Entity("DisplayControl.Domain.Operations.OutboxMessage", b =>
                {
                    b.HasOne("DisplayControl.Domain.Tenancy.Tenant", null)
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_outbox_messages_tenants");
                });

            modelBuilder.Entity("DisplayControl.Domain.Operations.TenantAuditEvent", b =>
                {
                    b.HasOne("DisplayControl.Domain.Tenancy.Tenant", null)
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_audit_events_tenants");
                });

            modelBuilder.Entity("DisplayControl.Domain.Playlists.Playlist", b =>
                {
                    b.HasOne("DisplayControl.Domain.Tenancy.Tenant", null)
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_playlists_tenants");
                });

            modelBuilder.Entity("DisplayControl.Domain.Playlists.PlaylistItem", b =>
                {
                    b.HasOne("DisplayControl.Domain.Tenancy.Tenant", null)
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_playlist_items_tenants");

                    b.HasOne("DisplayControl.Domain.Content.ContentVersion", null)
                        .WithMany()
                        .HasForeignKey("TenantId", "ContentVersionId")
                        .HasPrincipalKey("TenantId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_playlist_items_content_versions_tenant");

                    b.HasOne("DisplayControl.Domain.Playlists.PlaylistVersion", null)
                        .WithMany()
                        .HasForeignKey("TenantId", "PlaylistVersionId")
                        .HasPrincipalKey("TenantId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_playlist_items_versions_tenant");
                });

            modelBuilder.Entity("DisplayControl.Domain.Playlists.PlaylistVersion", b =>
                {
                    b.HasOne("DisplayControl.Domain.Tenancy.Tenant", null)
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_playlist_versions_tenants");

                    b.HasOne("DisplayControl.Domain.Playlists.Playlist", null)
                        .WithMany()
                        .HasForeignKey("TenantId", "PlaylistId")
                        .HasPrincipalKey("TenantId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_playlist_versions_playlists_tenant");
                });

            modelBuilder.Entity("DisplayControl.Domain.Scheduling.DesiredState", b =>
                {
                    b.HasOne("DisplayControl.Domain.Tenancy.Tenant", null)
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_desired_states_tenants");

                    b.HasOne("DisplayControl.Domain.Devices.Device", null)
                        .WithMany()
                        .HasForeignKey("TenantId", "DeviceId")
                        .HasPrincipalKey("TenantId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_desired_states_devices_tenant");

                    b.HasOne("DisplayControl.Domain.Scheduling.DeviceAssignment", null)
                        .WithMany()
                        .HasForeignKey("TenantId", "SourceDeviceAssignmentId")
                        .HasPrincipalKey("TenantId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_desired_states_device_assignments_tenant");

                    b.HasOne("DisplayControl.Domain.Scheduling.GroupAssignment", null)
                        .WithMany()
                        .HasForeignKey("TenantId", "SourceGroupAssignmentId")
                        .HasPrincipalKey("TenantId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_desired_states_group_assignments_tenant");

                    b.HasOne("DisplayControl.Domain.Scheduling.DesiredState", null)
                        .WithMany()
                        .HasForeignKey("TenantId", "SupersededByDesiredStateId")
                        .HasPrincipalKey("TenantId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_desired_states_superseded_by_tenant");
                });

            modelBuilder.Entity("DisplayControl.Domain.Scheduling.DesiredStateAsset", b =>
                {
                    b.HasOne("DisplayControl.Domain.Tenancy.Tenant", null)
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_desired_state_assets_tenants");

                    b.HasOne("DisplayControl.Domain.Content.ContentVersion", null)
                        .WithMany()
                        .HasForeignKey("TenantId", "ContentVersionId")
                        .HasPrincipalKey("TenantId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_desired_state_assets_content_versions_tenant");

                    b.HasOne("DisplayControl.Domain.Scheduling.DesiredState", null)
                        .WithMany()
                        .HasForeignKey("TenantId", "DesiredStateId")
                        .HasPrincipalKey("TenantId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_desired_state_assets_states_tenant");
                });

            modelBuilder.Entity("DisplayControl.Domain.Scheduling.DeviceAssignment", b =>
                {
                    b.HasOne("DisplayControl.Domain.Tenancy.Tenant", null)
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_device_assignments_tenants");

                    b.HasOne("DisplayControl.Domain.Devices.Device", null)
                        .WithMany()
                        .HasForeignKey("TenantId", "DeviceId")
                        .HasPrincipalKey("TenantId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_device_assignments_devices_tenant");

                    b.HasOne("DisplayControl.Domain.Playlists.PlaylistVersion", null)
                        .WithMany()
                        .HasForeignKey("TenantId", "PlaylistVersionId")
                        .HasPrincipalKey("TenantId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_device_assignments_playlist_versions_tenant");
                });

            modelBuilder.Entity("DisplayControl.Domain.Scheduling.GroupAssignment", b =>
                {
                    b.HasOne("DisplayControl.Domain.Tenancy.Tenant", null)
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_group_assignments_tenants");

                    b.HasOne("DisplayControl.Domain.Devices.DeviceGroup", null)
                        .WithMany()
                        .HasForeignKey("TenantId", "DeviceGroupId")
                        .HasPrincipalKey("TenantId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_group_assignments_groups_tenant");

                    b.HasOne("DisplayControl.Domain.Playlists.PlaylistVersion", null)
                        .WithMany()
                        .HasForeignKey("TenantId", "PlaylistVersionId")
                        .HasPrincipalKey("TenantId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_group_assignments_playlist_versions_tenant");
                });
#pragma warning restore 612, 618
        }
    }
}
